# =============================================================================
# SearxNG Rate Limiter Configuration
# =============================================================================
# Minimal configuration for FlowLab deployment

[botdetection.ip_limit]
# Basic rate limiting
link_token = true

[botdetection.ip_lists]
# IP filtering
link_token = true 